name: Maven Build

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: read-all

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
        cache-dependency-path: ${{ github.workspace }}/pom.xml
  
    - name: Build with Maven
      run: make build

